### ISSUE TITLE
[review-docs] Databases

### ISSUE THREAD

**Issue by isichei** [moj-analytical-services/user-guidance#107]
[docs](https://github.com/moj-analytical-services/user-guidance/blob/main/source/documentation/data-docs/curated-databases-docs/databases.md)

Might be worth adding section on creating database on the analytical platform in this?

Some templates we currently have to do this can be found here: https://github.com/moj-analytical-services/mojap-aws-tools-demo/

**Comment by neillturner** [comment]
linked added to docs by Various documentation fixes for outstanding Issues #193
