### ISSUE TITLE
[review-docs] airflow

### ISSUE THREAD

**Issue by isichei** [moj-analytical-services/user-guidance#112]
[docs](https://github.com/moj-analytical-services/user-guidance/blob/main/source/documentation/tools/airflow.md)

This was written fairly recently but worth reviewing again. Also worth noting we did a [Coffee and Coding on Airflow](https://github.com/moj-analytical-services/Coffee-and-Coding/tree/master/2020-04-27%20Airflow%20on%20AP) so might be worth also linking to that.

**Comment by neillturner** [comment]
this seems to be done now. closing.
