### ISSUE TITLE
Using Python with renv

### ISSUE THREAD

**Issue by ms130** [moj-analytical-services/user-guidance#131]
In [this section](https://user-guidance.services.alpha.mojanalytics.xyz/tools/package-management.html#using-r-renv-with-python-venv) of the guidance, the [site linked to](https://rstudio.github.io/renv/articles/python.html) makes no mention of `venv`. Looking at the site, I don't think the suggestion is to use R Renv with Python Venv, but how to activate Python integration within `renv`. Think this section should therefore be changed to reflect what the page actually recommends.

**Comment by neillturner** [comment]
fixed by Various documentation fixes for outstanding Issues #193
