### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by Thomas-Hirsch** [moj-analytical-services/user-guidance#17]
I've spotted a few areas where there are links to the old user guidance, which either redirect to new platform user guidance or 404s. Places I've spotted are:
- The first 3 links of the github guidance, as well as "Searchable" in the Private and Public Repos section
- Also on github guidance, "Choosing public or private repos" is broken as the section it should link to has a broken tag
- The link to Information Governance in the "Upload files to S3" section of the Amazon S3 page attempts to link to the nonexistent Information Governance section in the same page, rather than the dedicated IG chapter
- Further down on the same page, the link to the AWS Management Console in the Download or read files in S3 section is broken due to a superfluous `http//`
- The link to `Build and deploy guidance` [in this section of Data Pipelines](https://user-guidance.services.alpha.mojanalytics.xyz/data-pipelines.html#build-the-image) links to the old guidance
- In the Build and Deploy guidance, the links to Web app and Airflow Pipeline are both broken
- Under [Routes of support](https://user-guidance.services.alpha.mojanalytics.xyz/support.html#platform-support), the link to the Digitech slack channel is malformed
- Under [coding support in R & Python](https://user-guidance.services.alpha.mojanalytics.xyz/support.html#coding-support-r-amp-python), the link to reproducable [sic] examples is broken. Also reproducible is misspelled twice.
- The link to Advanced Deployment at the end of Common Answers and Solutions links to the old doc
- [this link in the annex](https://user-guidance.services.alpha.mojanalytics.xyz/annexes.html#step-2-set-up-your-platform-2fa-using-your-smartphone) includes a link to the old doc

Two additional notes:
1. There are several instances of bare URLs which I think were previously automatically turned into hyperlinks, but are now not hyperlinked.
2. All the View Source and Report a Problem links at the bottom of the page don't work.

**Comment by chudiemeagi** [comment]
In the “Using Github with the Platform” page, the link at the top to Full guidance, links to the very top of the guide, it should probably link to the section entitled “Creating an SSH Key” instead.
