### ISSUE TITLE
Add "too many redirects" to common errors and solutions

### ISSUE THREAD

**Issue by Thomas-Hirsch** [moj-analytical-services/user-guidance#18]
A common error people experience is Auth0 misremembering logins, giving an issue of "too many redirects". One solution (hinted at by the error message) is to clear your cookies; a more robust solution is to go to the magic url https://alpha-analytics-moj.eu.auth0.com/v2/logout to properly log you out so you can log back in again. There's no reference to this in the docs, so it would be useful to add.

**Comment by neillturner** [comment]
fixed by Various documentation fixes for outstanding Issues #193
