### ISSUE TITLE
Change instructions to copy from terminal when creating SSH key

### ISSUE THREAD

**Issue by chudiemeagi** [moj-analytical-services/user-guidance#27]
In the section on Jupyterlab under “Create Your SSH Key” it’d be helpful to let people know that to copy text from the terminal they should Ctrl + Insert rather than Ctrl + C. A simple fix, but not being able to copy my SSH key in github slowed me down quite a bit!

**Comment by neillturner** [comment]
fixed by Various documentation fixes for outstanding Issues #193
