### ISSUE TITLE
Re: 'Create a Derived Table Instructions'

### ISSUE THREAD

**Issue by vonbraunbates** [moj-analytical-services/user-guidance#312]
Problem with 'Create a Derived Table Instructions' (https://user-guidance.services.alpha.mojanalytics.xyz/tools/create-a-derived-table/instructions/)

Note that python 3.11 [https://docs.getdbt.com/faqs/core/install-python-compatibility](is not compatible) with `dbt-core`.  Please amend the venv setup section as follows:
update `python3 -m venv venv` to `python3.10 -m venv venv` 
delete the line `pip install --upgrade pip`
It took me a while to find out that this was the source of `dbt --version` producing ~20 lines of python errors.

Edit:
Now that we have a working branch for the new adaptor, we should test compatibility with Python 3.11.x (python latest). To this end -

- Create a Fresh Branch from the new adaptor main
- Test all major functions (models and seed deployment, tests etc.) with new python version
- If bugs are encountered, log so tickets can be created to remediate.
- Update User Guidance to reflect outcomes of testing (either we are now compatible, or we should be guiding users away from latest until we are)

**Comment by vonbraunbates** [comment]
There is also a line missing after `pip install -r requirements.txt` which is:
`pip install dbt-athena-adapter`
otherwise `dbt debug` produces the error:
```
1 check failed:
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "mojap", target "dev" invalid: Runtime Error
    Could not find adapter type athena!
```

**Comment by tamsinforbes** [comment]
thanks for this - will revisit once we have completed updates to the versions of dbt-core and dbt-athena-adapter we are using

**Comment by lalithanagarur** [comment]
- Using RStudio in AP Control Panel, version is Python 3.8.10. Can this be changed?
- In VSCode, using Python 3.11.2 to test.

**Comment by lalithanagarur** [comment]
PR ready for review [here](https://github.com/moj-analytical-services/user-guidance/pull/345).
