### ISSUE TITLE
Update add source instructions create-a-derived-table

### ISSUE THREAD

**Issue by tamsinforbes** [moj-analytical-services/user-guidance#322]
This [paragraph](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/create-a-derived-table/instructions/#sources) in the main instructions needs changing and instructions to users on how to add sources should be added.

Instructions something like
- start a new branch off main (so it is easily revertable if something goes wrong)
- add source database name exactly as it appears in Athena to the source_database_name.txt file
- make PR

Include information about when sources are updated eg: sources are automatically refreshed weekly when new sources will be added and existing sources updated.

[Link to file in user guidance repo to edit](https://github.com/moj-analytical-services/user-guidance/blob/main/source/documentation/tools/create-a-derived-table/instructions.md#sources)
From line 420

**Comment by Bharat-Dhiman** [comment]
[https://github.com/moj-analytical-services/user-guidance/pull/323](PR) for the changes.
