### ISSUE TITLE
Add guidance for renv (and one day prefer over conda?)

### ISSUE THREAD

**Issue by ben-lavelle** [moj-analytical-services/user-guidance#77]
I think we've talked about it before, but I think it'd be a huge help to the waves and waves of conda problems that people encounter to advertise the option of `renv` instead. A good number of projects in DASD are written in pure R, often with just a handful of dependencies like tidyverse packages, and conda is heavy-handed, weighty, and error-prone. 

Renv is relatively new to the scene, but is mature, light and sensible. I've recently seen a colleague who had no prior experience of environment management go from "Hey is there a way to make sure everyone is on the right verison" to a complete, merged and _understood_ renv solution in an hour. The [introductory documentation](https://rstudio.github.io/renv/articles/renv.html) is great so we'd barely need to do more than lift this.

> ⚠️  In my experience, the most difficult use cases for env management are deployed shiny apps. I haven't seen or tried working with renv here, but at a glance there is [guidance in the renv documentation](https://rstudio.github.io/renv/articles/docker.html) on using renv with Docker 🐳 . This could be added later.

I'd suggest:
- [ ] Add guidance on using renv for simple non-webapp R projects
- [ ] Add guidance on using renv in shiny apps
- [ ] Push renv over conda for simple non-apps?
- [ ] Push renv over conda for shiny apps?
- [ ] (Remove conda from base Rstudio deployments? @damacus is considering working on a lighter-weight image prioritising renv here)

**Comment by neillturner** [comment]
fixed by Various documentation fixes for outstanding Issues #193
