### ISSUE TITLE
Missing step in app deployment guidance for static apps

### ISSUE THREAD

**Issue by ian-rickard** [moj-analytical-services/user-guidance#97]
I believe that [this step](https://user-guidance.services.alpha.mojanalytics.xyz/rshiny-app.html#create-a-new-webapp), that is written in the guidance for deploying a Shiny app, is also necessary for deploying a static app, [but it doesn't seem to be there](https://user-guidance.services.alpha.mojanalytics.xyz/static-app.html#deploying-a-static-webapp).

**Comment by neillturner** [comment]
this has been added
