### ISSUE TITLE
Add information on deploying dash apps to documentation

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/user-guidance#98]
Current information limited to running dash apps on personal platform account - would be useful to have instructions on how to deploy properly via concourse as well.

Even a link to the relevant coffee & coding session would be useful  https://github.com/moj-analytical-services/Coffee-and-Coding/tree/master/2020-04-14%20Python%20webapps%20using%20Plotly%20Dash

Not sure what the process for adding things to the docs are? Should I go off and submit a PR myself, or does it have to go through more official channels?

**Comment by neillturner** [comment]
fixed by Various documentation fixes for outstanding Issues #193
